groups:
  - developers
recipes:
  mac_os_x:
    - osxdefaults::set_computer_name
attributes:
  osxdefaults:
    computername: endor
    homebrewalt:
      apps:
        - git-extras
      cask_apps:
        - 1password
        - adium
        - calibre
        - devonthink-pro
        - flux
        - handbrakecli
        - makemkv
        - textexpander3
        - things
        - torbrowser
        - vagrant
        - vlc
        - ynab
      cask_fonts:
        - anonymous-pro
        - sauce-code-powerline
        - source-code-pro
