recipes:
  mac_os_x:
    - applications::dnsmasq
    - applications::postgresql
    - osxdefaults::set_terminal_profile
attributes:
  homebrewalt:
    apps:
      - direnv
      - git-extras
    cask_apps:
      - cyberduck
      - hipchat
      - java
      - java7
      - pgadmin3
      - robomongo
      - slack
      - utc-menu-clock
      - virtualbox
    nodejs:
      apps:
        - bower
        - grunt-cli
        - gulp
        - express
        - express-generator
        - coffee-script
