recipes:
  mac_os_x:
    - applications::dnsmasq
    - applications::postgresql
    - osxdefaults::set_terminal_profile
    - osxdefaults::enable_safari_debug_menu
    - osxdefaults::enable_standard_function_keys
    - osxdefaults::finder_show_file_extensions
attributes:
  homebrewalt:
    taps:
      - nviennot/tmate
    apps:
      - boot2docker
      - casperjs
      - ctags
      - direnv
      - elixir
      - git-extras
      - go
      - maven
      - redis
      - rabbitmq
      - ruby-install
      - s3cmd
      - the_silver_searcher
      - tmux
      - tmate
    cask_apps:
      - cyberduck
      - hipchat
      - java
      - java7
      - pgadmin3
      - robomongo
      - slack
      - utc-menu-clock
      - virtualbox
    nodejs:
      apps:
        - bower
        - grunt-cli
        - gulp
        - express
        - express-generator
        - coffee-script
